### ISSUE TITLE
Help Option is Broken

### ISSUE THREAD

**Issue by PiyushSaini97** [Cloud-V/Fault#16]
Hi,
I'm trying to install Fault on Windows Subsystem for Linux (WSL2). I installed prerequisites for the software and all of them are working fine. However, when I try to install Fault in my system, it gives me an error. Find the image below-

![image](https://user-images.githubusercontent.com/85390797/123510391-ce554580-d698-11eb-96a0-89b25da3dd76.png)
 
I don't understand what the error is about.

Note: I did not install Atalanta or PODEM as they were optional and thought to use the software's pattern generation 

Please help.

Regards,
Piyush

**Comment by Zhaowenqing** [comment]
> Hi,
> I'm trying to install Fault on Windows Subsystem for Linux (WSL2). I installed prerequisites for the software and all of them are working fine. However, when I try to install Fault in my system, it gives me an error. Find the image below-
> 
> ![image](https://user-images.githubusercontent.com/85390797/123510391-ce554580-d698-11eb-96a0-89b25da3dd76.png)
> 
> I don't understand what the error is about.
> 
> Note: I did not install Atalanta or PODEM as they were optional and thought to use the software's pattern generation
> 
> Please help.
> 
> Regards,
> Piyush

I  also encountered this problem. Then I changed the swift version to 5.2, and the problem was solved.You can try this method

**Comment by donn** [comment]
@Zhaowenqing is correct: Fault supports Swift 5.2+ as shown in [INSTALLING.md](https://github.com/Cloud-V/Fault/blob/d59d45d307f48a5b3082571507a589ccc9beafbc/INSTALLING.md).

I'll add like a little GitHub badge to emphasize this in the Readme.

**Comment by donn** [comment]
Done.

**Comment by PiyushSaini97** [comment]
I was using the latest version of swift(5.4.1) for installation purpose and encountered this error. Is it that the software can be built using only swift 5.2?

**Comment by donn** [comment]
Um, not really. That's quite interesting. I'll have to take another look.

**Comment by PiyushSaini97** [comment]
Hi. I was able to install the software this time with the help of swift 5.3. I had to move from WSL to ubuntu OS for the installation.
While installing I ran into two other problems. 
1) I was not able to install the atalanta and podem files. It gave me error of URLexecutable.
2) After going through all the steps given in https://github.com/Cloud-V/Fault/blob/d59d45d307f48a5b3082571507a589ccc9beafbc/INSTALLING.md, I was shown a message "installed". But when I tried running the software, my system prompted "fault not found". I double checked the bin folder to ensure that it was installed.

![error_Fault](https://user-images.githubusercontent.com/85390797/123695348-1088ad80-d878-11eb-986e-65e02969aaf3.png)

Please help.

**Comment by donn** [comment]
The warnings are expected.

The issue is actually what you see right after Swift's warnings: `sh: 1: curl: not found`. You need to install curl: `sudo apt-get install curl`. There's a slight API deviation between Linux and macOS in Swift that requires Linux to use a slightly older API, triggering those warnings.

As for Fault not being found, that's because your `~/bin` folder is not in PATH. You'll need to add `export PATH=$HOME/bin:$PATH;` to your `~/.profile`. 

Alternatively, you can do `INSTALL_DIR=/usr/local/bin swift install.swift` to install to a folder known to be in PATH.

As an aside, you're invoking the Atalanta/PODEM installers using EXEC_PREFIX=</usr/local/bin>. This is not a valid path: the tutorial shows the `<>` to indicate that this can be changed.

**Comment by PiyushSaini97** [comment]
Thank you for your time. Fault installed perfectly. But this time I encountered another problem. When I tried `fault --help`, it prompted me to invoke it again. 

![error_fault_help](https://user-images.githubusercontent.com/85390797/123714811-aaf6ea00-d894-11eb-954f-08a28eba2caa.png)

I encountered this for `fault synth --help` and `fault tap --help` as well. Other help commands worked.

Also, when I tried installing atalanta once again it gave me another error (referenced in the image).

**Comment by donn** [comment]
Confirmed issue. I think I botched it while trying to enforce "required" flags...

**Comment by PiyushSaini97** [comment]
So should I reinstall Fault in order to use the updated one?

**Comment by donn** [comment]
Give me a moment to push the update.

**Comment by PiyushSaini97** [comment]
Ok. Thank you for your time.
