### ISSUE TITLE
Humble request to ensure this as well

### ISSUE THREAD

**Issue by mdzakirhussain** [Cloud-V/Fault#9]
https://github.com/Cloud-V/Fault/blob/75dd9eafb5c5f05c1c34f3636a571875de1fa191/Dockerfile#L35

I am getting the following error

root@zakir-virtual-machine:/share# cp . /share/Fault
cp: -r not specified; omitting directory '.'

**Comment by donn** [comment]
You are not supposed to run the Dockerfile commands manually. These are used by https://hub.docker.io to construct a virtual machine.
